# Generated by Django 4.2.1 on 2023-06-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='start_date',
            field=models.DateField(),
        ),
    ]
