# Generated by Django 4.2.1 on 2023-06-04 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hackathonsubmission',
            unique_together={('hackathon', 'team')},
        ),
    ]
